config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => "admin#index"
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete  'logout' => :destroy
  end
  scope '(:locale)' do
    resources :users
    resources :orders do
      get :update_ship_date, on: :member
    end
    resources :line_items
    resources :carts
    resources :products do
      get :who_bought, on: :member
    end
    resources :pay_types
    root to: 'store#index', as: 'store'
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
      # Rails Play Time - Ch.10 Depot_e
      current_item.price = current_item.product.price
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  attr_accessible :cart_id, :product_id, :product, :quantity
  belongs_to :order
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :address, :email, :name, :pay_type_id

  has_many :line_items, dependent: :destroy
  belongs_to :pay_type

  validates :name, :address, :email, presence: true
  validates :pay_type_id, presence:true

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/pay_type.rb
class PayType < ActiveRecord::Base
  attr_accessible :name

  has_many :order
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :image_url, :price, :title
  has_many :line_items
  has_many :orders, through: :line_items

  before_destroy :ensure_not_referenced_by_any_line_item

  validates :title, :description, :image_url, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  # Rails Play Time - Ch.7 Depot_b
  validates :title, uniqueness: true, length: { :minimum => 10, :message => :too_short }
  validates :image_url, allow_blank: true, format: {
    with:    %r{\.(gif|jpg|png)$}i,
    message: 'は、gif,jpg,png画像のURLでなければなりません'
  }
  # Rails Play Time - Ch.10 Depot_e
  validates :image_url, uniqueness: true
  validates :price, numericality: {less_than_or_equal_to: 1000}

  private

  # この商品を参照している品目がないことを確認する
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, '品目が存在します')
      return false
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password_digest, :password, :password_confirmation
  validates :name, presence: true, uniqueness: true
  has_secure_password

  after_destroy :ensure_an_admin_remains

  private
  def ensure_an_admin_remains
    if User.count.zero?
      raise "最後のユーザーは削除できません"
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_orders = Order.count
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_filter :authorize, only: [:create, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
      logger.error "無効なカート#{params[:id]}にアクセスしようとしました"
      SystemNotifier.error_occured(e).deliver
      redirect_to store_url, notice: '無効なカートです'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @cart }
      end
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to store_url }
      format.js
      format.json { head :no_content }
    end
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  skip_before_filter :authorize

  def index
    if params[:set_locale]
      redirect_to store_path(locale: params[:set_locale])
    else
      @products = Product.order(:title)
      @cart = current_cart
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    params[:action] = :edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url,
          notice: "User #{@user.name} was successfully created." }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    if @user.authenticate(params[:user][:current_password])
      params[:user].delete :current_password
      respond_to do |format|
        if @user.update_attributes(params[:user])
          format.html { redirect_to users_url,
            notice: "User #{@user.name} was successfully updated." }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to edit_user_path(@user), notice: 'Current password is incorrect'
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    begin
      @user.destroy
      flash[:notice] = "Successfully destroyed... user: #{@user.name}"
    rescue Exception => e
      flash[:notice] = e.message
    end

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition, attributes = {}, &block)
    if condition
      attributes["style"] = "display: none"
    end
    content_tag("div", attributes, &block)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pay_types_helper.rb
module PayTypesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>ようこそ</h1>

現在の時刻は、<%= Time.now %>です。
We have <%= pluralize(@total_orders, "order") %>.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">
  <div id="banner">
    <%= form_tag store_path, class: 'locale' do %>
      <%= select_tag 'set_locale',
        options_for_select([
            ['English', 'en'],
            ["日本語".html_safe, 'ja']
          ], I18n.locale.to_s),
        onchange: 'this.form.submit()' %>
      <%= javascript_tag "$('.locale input').hide()" %>
    <% end %>
    <%= image_tag("logo.png") %>
    <%= @page_title || t('.title') %>
  </div>
  <div id="columns">
    <div id="side">
      <div id="cart">
        <% if @cart %>
          <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
            <%= render @cart %>
          <% end %>
        <% end %>
      </div>

      <ul>
        <li><a href="/"><%= t('.home') %></a></li>
        <li><a href="/faq"><%= t('.questions') %></a></li>
        <li><a href="/news"><%= t('.news') %></a></li>
        <li><a href="/contact"><%= t('.contact') %></a></li>
      </ul>

      <% if session[:user_id] %>
      <ul>
        <li><%= link_to 'Orders', orders_path %></li>
        <li><%= link_to 'Products', products_path %></li>
        <li><%= link_to 'Users', users_path %></li>
      </ul>
        <%= button_to 'logout', logout_path, method: :delete %>
      <% end %>
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/order_notifier/received.html.erb
<h3>Dear <%= @order.name %></h3>

<p>Pragmaticストアでのご注文、誠にありがとうございます。<br>
あなたがご注文されたのは以下の品目です。</p>

<table>
  <tr>
    <th colspan="2">数量</th><th>説明</th>
  </tr>
<%= render @order.line_items %>
</table>

<p>あなたのご注文を発送する際には、別途電子メールでご連絡致します。</p>

app/views/order_notifier/received.text.erb
Dear <%= @order.name %>

Pragmaticストアでのご注文、誠にありがとうございます。
あなたがご注文されたのは以下の品目です。
<%= render @order.line_items %>
あなたのご注文を発送する際には、別途電子メールでご連絡致します。

app/views/order_notifier/shipped.html.erb
<h3>Pragmaticでのご注文商品を発送しました</h3>
<p>ご注文の商品を発送したことをお知らせ致します。</p>

<table>
  <tr>
    <th colspan="2">数量</th><th>説明</th>
  </tr>
<%= render @order.line_items %>
</table>

app/views/order_notifier/shipped.text.erb
Pragmaticでのご注文商品を発送しました
ご注文の商品を発送したことをお知らせ致します。

<%= render @order.line_items %>

app/views/system_notifier/error_occured.text.erb
Depot app. にエラーが発生しました。

Error details:

<%= @error.message %>

--
SystemNotifier#error_occured